
export default new Map([
["src/content/blog/beginning-your-open-source-journey.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fbeginning-your-open-source-journey.mdx&astroContentModuleFlag=true")],
["src/content/blog/concluding-springboard-next-adventure.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fconcluding-springboard-next-adventure.mdx&astroContentModuleFlag=true")],
["src/content/blog/frontend-migration-note.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffrontend-migration-note.mdx&astroContentModuleFlag=true")],
["src/content/blog/evaluating-machine-translation-models.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fevaluating-machine-translation-models.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-big-are-cryptographic-primes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-big-are-cryptographic-primes.mdx&astroContentModuleFlag=true")],
["src/content/blog/introduction-to-zkps.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fintroduction-to-zkps.mdx&astroContentModuleFlag=true")],
["src/content/blog/jp-en-translator-walkthrough.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fjp-en-translator-walkthrough.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-ask-for-help-in-oss-communities.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-ask-for-help-in-oss-communities.mdx&astroContentModuleFlag=true")],
["src/content/blog/launching-mitchell-technology-consulting.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Flaunching-mitchell-technology-consulting.mdx&astroContentModuleFlag=true")],
["src/content/blog/python-features-in-js.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpython-features-in-js.mdx&astroContentModuleFlag=true")],
["src/content/blog/software-engineer-interview-questions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsoftware-engineer-interview-questions.mdx&astroContentModuleFlag=true")],
["src/content/blog/sql-order-of-execution.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsql-order-of-execution.mdx&astroContentModuleFlag=true")],
["src/content/blog/updated-website.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fupdated-website.mdx&astroContentModuleFlag=true")],
["src/content/blog/visual-intuition-differential-privacy-part1.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fvisual-intuition-differential-privacy-part1.mdx&astroContentModuleFlag=true")],
["src/content/blog/nested-route/introducing-multi-part-posts-with-nested-routing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fnested-route%2Fintroducing-multi-part-posts-with-nested-routing.mdx&astroContentModuleFlag=true")]]);
		